// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdBrcuBjdudj1M0A1alNJFqMC9rUfZdqU',
    appId: '1:212136874688:web:f92c5aece18478c561d325',
    messagingSenderId: '212136874688',
    projectId: 'virtual-fashion-hub',
    authDomain: 'virtual-fashion-hub.firebaseapp.com',
    storageBucket: 'virtual-fashion-hub.firebasestorage.app',
    measurementId: 'G-BDKCE1MC0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0opBozNnBHKax_yTt6EmjuP6DP13ocsg',
    appId: '1:212136874688:android:f0fa900c20dc605161d325',
    messagingSenderId: '212136874688',
    projectId: 'virtual-fashion-hub',
    storageBucket: 'virtual-fashion-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbf1LFNda6gZi5VruE9zDxMx4ue16bYeA',
    appId: '1:212136874688:ios:8aa176fabfe56e7861d325',
    messagingSenderId: '212136874688',
    projectId: 'virtual-fashion-hub',
    storageBucket: 'virtual-fashion-hub.firebasestorage.app',
    iosBundleId: 'com.example.virtualTryonWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbf1LFNda6gZi5VruE9zDxMx4ue16bYeA',
    appId: '1:212136874688:ios:8aa176fabfe56e7861d325',
    messagingSenderId: '212136874688',
    projectId: 'virtual-fashion-hub',
    storageBucket: 'virtual-fashion-hub.firebasestorage.app',
    iosBundleId: 'com.example.virtualTryonWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdBrcuBjdudj1M0A1alNJFqMC9rUfZdqU',
    appId: '1:212136874688:web:8c5337b242fffb9361d325',
    messagingSenderId: '212136874688',
    projectId: 'virtual-fashion-hub',
    authDomain: 'virtual-fashion-hub.firebaseapp.com',
    storageBucket: 'virtual-fashion-hub.firebasestorage.app',
    measurementId: 'G-596MB2MSX1',
  );
}
